version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - ./*.html
    - favicon.ico
    - styles/*
    - images/*    
    - dist/bundle.js
    - cv.pdf